#!/usr/bin/env bash

function setup_anaconda_packages () {
  conda install \
      scikit-learn \
      scikit-image \
      theano \
      joblib \
      seaborn \
      -y
  conda install -c https://conda.anaconda.org/mutirri \
      pyaudio \
      pudb \
      -y
}
