#!/usr/bin/env bash

psauxkill () {
    if [ "$1" = "-9" ]
    then
        kill -9 `ps -axo pid,command | grep -v "awk /$2/" | awk "/$2/" | awk '{print $1}'`
    else
        kill `ps -axo pid,command | grep -v "awk /$1/" | awk "/$1/" | awk '{print $1}'`
    fi
}
