#!/usr/bin/env bash

psauxkill () {
    if [ "$1" = "-9" ]
    then
        kill -9 `ps aux | grep -v "awk /$2/" | awk "/$2/" | awk '{print $2}'`
    else
        kill `ps aux | grep -v "awk /$1/" | awk "/$1/" | awk '{print $2}'`
    fi
}
