#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

source scripts/git/setup-gitconfig
setup_gitconfig

source scripts/anaconda/setup-anaconda
source scripts/anaconda/setup-anaconda-packages
setup_anaconda
setup_anaconda_packages

source scripts/zsh/setup-antigen
setup_antigen

source scripts/zsh/setup-theme
setup_theme

source scripts/dot/setup-dotfiles
setup_dotfiles

echo ''
echo '  All installed!'
